export type TSideMenu = {
  Id: number;
  App: string;
  AppId: number;
  Value: boolean;
  UserId: number;
  IconUrl: string;
  RightsID: number;
  ScreenID: number;
  ModuleID: number;
  CompanyId: number;
  RightName: string;
  TargetUrl: string;
  ScreenName: string;
  ScreenAlias: string;
  IsFavorite: boolean;
  ModuleTypeId: number;
  TblUserRightslst: any;
  ModuleDescription: string;
  ModelMenuControllName: string;
  MenuControllName: null | string;
  RouteUrl: string;
  ScreenDescription: string;
  children: TChildren[];
};
export type TChildren = {
  App: string;
  AppId: number;
  CompanyId: number;
  IconUrl: string;
  Id: number;
  IsFavorite: boolean;
  MenuControllName: string | null;
  ModelMenuControllName: string;
  ModuleDescription: string;
  ModuleID: number;
  ModuleTypeId: number;
  RightName: string;
  RightsID: number;
  RouteUrl: string;
  ScreenAlias: string;
  ScreenDescription: string;
  ScreenID: number;
  ScreenName: string;
  TargetUrl: string;
  TblUserRightslst: string | null;
  UserId: number;
  Value: boolean;
};
